### ISSUE TITLE
Security: Risky First deposit in function calcDepositAmounts

### ISSUE THREAD

**Issue by smartsmartsec** [gammaswap/v1-implementations#179]
## Impact

- **Denial of Service**
- **Escalation of Privileges**
- **Other:** The first depositor can obtain a disproportionate amount of the pool's shares when reserves are initially zero, potentially monopolizing pool ownership.

## **Affected component(s)**

function `calcDepositAmounts` in CPMMShortStrategy.sol

## Attack vector(s)

An attacker can trigger this vulnerability by being the first to deposit tokens in a newly created pool where the initial reserves are zero.

## **Suggested description of the vulnerability for use in the CVE**

In Gammaswap, there exists a vulnerability in the **`calcDepositAmounts`** function where, if it is the first deposit to the pool and both reserve0 and reserve1 are zero, the function allows the depositor to claim nearly all the shares of the pool. This can result in an unintended escalation of privileges and severe economic impact by enabling the first depositor to disproportionately control the pool.

## **Discoverer(s)/Credits**

xFuzz

## Proposed Solution

Implement checks to prevent the calcDepositAmounts function from executing if both reserve0 and reserve1 are zero at the time of the first deposit. Alternatively, a mechanism to distribute initial shares more equitably among early depositors could be considered. Additionally, including a safeguard that requires minimum initial liquidity to be provided could mitigate such risks.

## **Reference(s)**

- https://arbiscan.io/address/0x251EEFD05E7fde831Ec2c46b51706ad7D68deA4c?utm_source=immunefi#code
- https://code4rena.com/reports/2022-01-insure#h-06-the-first-depositor-to-a-pool-can-drain-all-users

**Comment by 0xDanr** [comment]
I believe this is referring to inflation attacks. There's a requirement within DeltaSwap, UniswapV2, and SushiSwap that a minimum amount of liquidity equivalent to 1000 must be lost by the first depositor to deal with inflation attacks. The GammaPool also has this requirement. I think this is the same solution you are referring to. Please refer to our bounty in immunefi, if you'd like to point out more issues.
